FROM node:22.17

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY frontend/pnpm-lock.yaml frontend/package.json ./

RUN pnpm install --frozen-lockfile

COPY frontend/. .

EXPOSE 5173

CMD ["pnpm", "dev"]