version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/data:/app/data
    ports:
      - "8080:8080"
    working_dir: /app
    restart: unless-stopped
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    restart: unless-stopped
