FROM golang:1.23

RUN apt-get update && apt-get install -y gcc

WORKDIR /app

RUN mkdir -p /app/bin

COPY backend/go.mod backend/go.sum ./

RUN go mod download

COPY backend/. .

RUN go build -o /app/bin/server ./cmd/http

CMD ["/app/bin/server"]