version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/data:/app/data
    ports:
      - "8080:8080"
    working_dir: /app
    restart: unless-stopped
