definitions:
  request.CheckVoucher:
    properties:
      date:
        type: string
      flightNumber:
        type: string
    type: object
  request.GenerateVoucher:
    properties:
      aircraft:
        type: string
      date:
        type: string
      flightNumber:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  response.CheckVoucher:
    properties:
      exists:
        type: boolean
    type: object
  response.GenerateVoucher:
    properties:
      seats:
        items:
          type: string
        type: array
      success:
        type: boolean
    type: object
  response.GetVoucher:
    properties:
      aircraftType:
        type: string
      createdAt:
        type: string
      crewId:
        type: string
      crewName:
        type: string
      flightDate:
        type: string
      flightNumber:
        type: string
      id:
        type: integer
      seat:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /api/v1/voucher:
    get:
      consumes:
      - application/json
      parameters:
      - description: default is 1
        in: query
        name: page
        type: integer
      - description: default is 10
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.GetVoucher'
            type: array
      summary: Get all vouchers
      tags:
      - Voucher
  /api/v1/voucher/check:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.CheckVoucher'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CheckVoucher'
      summary: Check voucher by flight number and date
      tags:
      - Voucher
  /api/v1/voucher/generate:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.GenerateVoucher'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GenerateVoucher'
      summary: Generate voucher
      tags:
      - Voucher
swagger: "2.0"
